### ISSUE TITLE
Document `ans`

### ISSUE THREAD

**Issue by nyarly** [PaddiM8/kalker#101]
Swtiching from `bc` to `kalker`, I was missing `last` and had to come to the github issues to discover `ans`.

A line in the `help` output (maybe under a  `Predefined Variables` heading) would be great for discovery.

Very happy to submit a PR if you want

**Comment by PaddiM8** [comment]
Ah yes that should be documented better. You seem to have some kind of idea where one could put it. I would gladly merge a PR!
