### ISSUE TITLE
[Windows] Publish a 32-bit version of this app

### ISSUE THREAD

**Issue by xmha97** [PaddiM8/kalker#107]
Please publish a 32-bit version of this app.
I want to run the Kalker on Windows 7 (32-bit).

**Comment by PaddiM8** [comment]
Compiling for different architectures is a bit of a pain with one of the libraries I'm using, so the pre-compiled binaries are going to be quite limited for now. However, you could install Rust+cargo and then run `cargo install kalker` and that should be enough to get it installed. Is just going to take a few minutes to compile.
