### ISSUE TITLE
Convert number to hex

### ISSUE THREAD

**Issue by not-matthias** [PaddiM8/kalker#109]
As far as I know, it's currently only possible to display a hexadecimal number as decimal by entering it with `0x` or `_16`. It would be neat to have a function to convert a decimal number to hexadecimal. 

Example: 
```
>> hex(123456)
0x1e240
```

**Comment by PaddiM8** [comment]
This was definitely needed! I ended up making a "base" command instead of having a function, since numbers aren't represented as a particular number base under the hood. Now you will be able to do eg. `base 16` and get all results in hexadecimal (as well as decimal).

**Comment by not-matthias** [comment]
Thank you!
