### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by tprodanov** [PaddiM8/kalker#111]
Good day,

I tried to compile `kalker` from scratch with `RUST_BACKTRACE=1 cargo build --release`, and it fails with the folloiwing stderr:
```
  ../../gmp-src/tests/misc.c: In function 'seed_from_urandom':
  ../../gmp-src/tests/misc.c:109:3: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
    109 |   fread (buf, 1, 6, fs);
        |   ^~~~~~~~~~~~~~~~~~~~~
  make[3]: *** [Makefile:3013: test-suite.log] Error 1
  make[2]: *** [Makefile:3121: check-TESTS] Error 2
  make[1]: *** [Makefile:4566: check-am] Error 2
  make: *** [Makefile:524: check-recursive] Error 1
  thread 'main' panicked at 'Program failed with code 2: "make" "-j" "12" "check"', /home/timofey/.cargo/registry/src/github.com-1ecc6299db9ec823/gmp-mpfr-sys-1.5.0/build.rs:1196:13
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
     1: core::panicking::panic_fmt
               at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
     2: build_script_build::execute
     3: build_script_build::make_and_check
     4: build_script_build::build_mpfr
     5: build_script_build::compile_libs
     6: build_script_build::main
     7: core::ops::function::FnOnce::call_once
```

As far as I can see, there is one failed test for MPFR 4.2.0 (`tsprintf`), perhaps it is not your issue, but just wanted to let you know.

**Comment by PaddiM8** [comment]
That is good to know indeed! What system are you on? Haven't seen this before

**Comment by tprodanov** [comment]
I am on arch-based `EndeavourOS`, rust `1.67.0`.

**Comment by PaddiM8** [comment]
Strange! Doesn't happen for me on Arch on rust 1.67.0. It might be something `gmp-mpfr-sys` has influence over. Thanks, for letting me know about it, I will keep this in mind.

For now I'm not sure if I can do anything about it, but I'll reopen the issue if anything comes up!

**Comment by crabvk** [comment]
Same issue. Building in [clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot).

**Comment by DanielChesters** [comment]
Same issue on an Arch clean chroot, but not in "standard" build on Arch. Maybe a missing dependency for the chroot :thinking:. I add compilation log ([kalker-2.0.4-1-x86_64-build.log](https://github.com/PaddiM8/kalker/files/13328255/kalker-2.0.4-1-x86_64-build.log))

**Comment by crabvk** [comment]
The problem persists with the latest code from the master, so why is this issue closed?
