### ISSUE TITLE
Or and not logic symbols swapped in help and on website

### ISSUE THREAD

**Issue by tkkot** [PaddiM8/kalker#112]
On the [kalker.xyz](kalker.xyz) website and in the output of `help` command, when describing the tab-insertion of special characters, the symbols for **OR** and **NOT** logical operators are swapped.

help:
```
or becomes ¬
not becomes ∨ 
```
website:
![image](https://user-images.githubusercontent.com/38937849/217834068-f4cd0d14-ed84-451d-a130-c500d9faf8ca.png)

**Comment by PaddiM8** [comment]
Thanks! Should be fixed now.
