### ISSUE TITLE
 _ returns the value of the last executed expression value

### ISSUE THREAD

**Issue by Sergo1217** [PaddiM8/kalker#114]
I want to _ work like in Python
![Capture40](https://user-images.githubusercontent.com/16447886/223070061-e35efb93-d59a-4c28-9b5d-0528f460a0bd.png)

**Comment by romanw** [comment]
Use `ans` instead of `_` e.g. `ans * 2`

**Comment by PaddiM8** [comment]
This would unfortunately not longer make it possible to have underscores in variables, due to the way multiplication works.
