### ISSUE TITLE
Build error with `yay -S kalker` in Manjaro

### ISSUE THREAD

**Issue by imprimatur13** [PaddiM8/kalker#116]
`==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: kalker-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
kalker - exit status 4`
Unsure what to do here; any advice?

**Comment by PaddiM8** [comment]
Hm are you able to get more information out of it? You can always install it using `cargo install kalker` otherwise.

**Comment by PaddiM8** [comment]
Closing until there is more information.
