### ISSUE TITLE
Feature Request: Add support for bitwise operators

### ISSUE THREAD

**Issue by JS-Zheng** [PaddiM8/kalker#120]
**Description:**
While kalker currently supports functions like `bitand` and `bitor` for performing bitwise operations, I believe incorporating traditional bitwise operators (e.g., `&` for AND, `|` for OR, `~` for NOT) directly into the calculator would greatly enhance its usability and appeal to programmers.

**Benefits:**
1. Improved readability: The inclusion of bitwise operators will make expressions more concise and familiar to programmers who are accustomed to working with bitwise operations.
2. Simplified syntax: The availability of native bitwise operators eliminates the need for verbose function calls, such as `bitand()` and `bitor()`, resulting in cleaner and more intuitive code.
3. Enhanced productivity: By reducing the amount of code required to perform bitwise operations, developers can write calculations more efficiently and save time.

**Example:**
```
Input:
    x = 10
    y = 7
    z = x & y
    z

Output:
    2
```

I believe the inclusion of native bitwise operators in Kalker would be highly beneficial for developers working with calculations involving bitwise operations. Thank you for considering this feature request.

**Comment by PaddiM8** [comment]
I do agree that this would be useful. Unfortunately the `|` symbol is already used as a short-hand for the `abs` function, so using that wouldn't be possible. The others are fine, but it feels a bit weird to have those but not OR. I can't figure out a good alternative, so I'll close this issue, but let me know if you come up with something.
