### ISSUE TITLE
kalker doesn't follow XDG specification

### ISSUE THREAD

**Issue by felixsanz** [PaddiM8/kalker#123]
the file `history.txt` should be inside `XDG_DATA_HOME` or `XDG_CACHE_HOME`, but not `XDG_CONFIG_HOME`.

So... not `.config/kalker/history.txt` as is not a configuration file. Instead it should be inside `.cache` or `.local/share` (not sure about this, but probably .cache)

**Comment by PaddiM8** [comment]
Yeah I think it XDG_CACHE_HOME will be good.
