### ISSUE TITLE
Variable assignment doesn't work

### ISSUE THREAD

**Issue by timokoesters** [PaddiM8/kalker#141]
![image](https://github.com/PaddiM8/kalker/assets/25297359/1d834cdb-ead6-4e69-8527-790b980ba417)

It doesn't work when I try it online on kalker.xyz, but it works in my local installation of version 2.1.0

PS: I hope it's alright if I open a few issues one after another :)

**Comment by PaddiM8** [comment]
It did set the the variable, but it returned an error message as well haha. Thanks! Should be fixed now
