### ISSUE TITLE
Very numbers become complex numbers?

### ISSUE THREAD

**Issue by timokoesters** [PaddiM8/kalker#147]
![image](https://github.com/PaddiM8/kalker/assets/25297359/e5e2e344-1cb2-40e3-8a11-93fc5d004bda)
![image](https://github.com/PaddiM8/kalker/assets/25297359/8e0e4ad4-5b5a-42f0-8bf1-d4ff2f3ff307)

![image](https://github.com/PaddiM8/kalker/assets/25297359/eff9c4d7-d072-45a0-8dee-4cb9057d5535)

No idea what's going on here, but the results are definitely wrong

**Comment by PaddiM8** [comment]
Oops, that was a regression in the latest release. Should be fixed now
