### ISSUE TITLE
`f(` hangs the repl

### ISSUE THREAD

**Issue by Noah765** [PaddiM8/kalker#157]
Typing `f(` and then pressing Enter will hang the repl. No further characters are processed.
I'm using kalker v2.2.0 and cannot currently build newer versions of kalker to confirm that this is still a problem.
This is not a problem if you don't use the repl, e.g. `kalker 'f('` produces the correct output: `Unexpected token: 'Eof'.`.

**Comment by PaddiM8** [comment]
Hmm doesn't happen for me. Are you sure it hangs? It shouldn't submit, but it should still let you type. When you have an open parenthesis it appends a new line when you press enter instead of submitting

**Comment by Noah765** [comment]
On closer inspection, it doesn't seem to be hanging. I will close this as it looks like this behaviour is intentional.
May I ask what is the reason for this behaviour? When I close the parenthesis and evaluate the expression, it always seems to return `Unexpected token: 'Newline'.`, so newlines as part of an expression don't ever seem to be valid.
