### ISSUE TITLE
Support × and ÷

### ISSUE THREAD

**Issue by abrudz** [PaddiM8/kalker#35]
Since you allow Unicode symbols, it'd be nice to use `×` and `÷` for multiplication and division, with tab completion on `*` and `/` too.

**Comment by PaddiM8** [comment]
Indeed. More symbols like this would make it more readable. Also things like eg. atan to tan⁻¹ and such. 
* \* to × 
* / to ÷
* atan to tan⁻¹  (and for the others as well)
* Maybe something like x_n to xₙ, that would also work for log.
* Maybe cbrt to ∛
* ...

**Comment by abrudz** [comment]
Just watch out, as traditional mathematical notation is inherently ambiguous.

For example, _f_ ²(_x_) is _f_(_f_(_x_)) but sin² _x_ is (sin _x_)².

So if _g_(_x_)=sin _x_, then is _g_ ²(x) equal to sin sin _x_ or (sin _x_)²

**Comment by PaddiM8** [comment]
> Just watch out, as traditional mathematical notation is inherently ambiguous.
> 
> For example, _f_ ²(_x_) is _f_(_f_(_x_)) but sin² _x_ is (sin _x_)².
> 
> So if _g_(_x_)=sin _x_, then is _g_ ²(x) equal to sin sin _x_ or (sin _x_)²

Wow, I see, thank you! I will have to do some reading about this kind of things then, to make sure it makes sense, and perhaps document some things a bit more.

sin²x syntax is definitely something I'll want to implement, forgot about that.

**Comment by PaddiM8** [comment]
Multiplication sign, division sign, arc functions, lowered digits, and cbrt now have unicode symbols!
