### ISSUE TITLE
Name collision with KDE Kalk 

### ISSUE THREAD

**Issue by gabm** [PaddiM8/kalker#39]
KDE Kalk is also a calculator from the KDE project: https://github.com/KDE/kalk

I understand it is different from this project? I installed "kalk" from the AUR and was surprised get a UI ... maybe you are still on time to rename? I know this hurts, but its unfortunate that we have two tools with the same functional scope with the same name :/

**Comment by PaddiM8** [comment]
Yeah there seems to be quite a few programs with this name, and it's quite a common word in various languages. I didn't actually expect this to get any attention, so I wasn't bothered by this. I'm thinking a solution could be to add something to "kalk", but I'm not sure what. Hm.

**Comment by gabm** [comment]
it seems your program hit a sweet spot on HN :) 

In the end its not my business, but from experience you should try to find a name that is distinct from similar products and original.. tough, i know ;)

**Comment by PaddiM8** [comment]
> it seems your program hit a sweet spot on HN :)
> 
> In the end its not my business, but from experience you should try to find a name that is distinct from similar products and original.. tough, i know ;)

I have been thinking about the name a bit lately, and have been wanting to make it more recognisable. Just have to find a good one that isn't too different haha. `kalky` or something maybe.

**Comment by gabm** [comment]
:cry: https://github.com/JB1905/kalky

**Comment by PaddiM8** [comment]
> cry https://github.com/JB1905/kalky

Hmm, seems quite inactive though, so maybe the author is fine with it if I ask them. Hard to find a good completely unique name.

**Comment by abrudz** [comment]
Maybe _skalk_ because it handles mathematical **s**ymbols?

**Comment by PaddiM8** [comment]
> Maybe _skalk_ because it handles mathematical **s**ymbols?

Hm, sounds a bit weird to me since it's a word in Swedish that sounds a bit negative in a way. Hmmm

**Comment by gabm** [comment]
skalk doesn't sound too bad to me.. 

`yak - yet another kalk(ulator)`

**Comment by PaddiM8** [comment]
Hm yeah, JB1905 isn't planning to update "kalky" and was fine with the name being used. These are, in my opinion, two pretty good options that don't sound too different from "kalk". Skalk makes sense, and does actually look good. The only problem I have with "skalk" is its meaning in my native language haha (while kalky is part of the word for calculator), so it will be a difficult decision.

**Comment by abrudz** [comment]
Skalky?

**Comment by PaddiM8** [comment]
So, I've asked around a bit to hear what people like. Quite literally everyone I've asked has prefered (a new option): "kalker", over the other options. I don't know though, doesn't feel as concise as "kalk". A good option may even be to add some word or something to kalk, eg. sym**kalk**, but then the word before/after would have to fit in and make sense as well (and be short)...

**Comment by PaddiM8** [comment]
It's now renamed to kalker! Although, the internal library is still called kalk. The website and program are the ones called "kalker", since those are the ones you search/download/install/whatever.

**Comment by fluunke** [comment]
You'll forever be kalk in our hearts
