### ISSUE TITLE
Web version: Completion for special symbols doesn't include parentheses

### ISSUE THREAD

**Issue by abrudz** [PaddiM8/kalker#40]
The documentation says that e.g. `sum` becomes `Σ()` but in in the web version it only becomes `Σ`.

So too, it says `(` becomes `()` but this doesn't work.

In addition, enclosing groups like `⌈⌉` do nove move the web cursor inside.

**Comment by PaddiM8** [comment]
Hm yeah that would be nice. I had some troubles doing this in the past, but it may be easier now since I completely changed the way the input field works. I'll look into it.

**Comment by PaddiM8** [comment]
Should work now!
