### ISSUE TITLE
Need for curated list of new features & fixes, for contributions.

### ISSUE THREAD

**Issue by hanani8** [PaddiM8/kalker#45]
I am using Kalk for a few days now, and I am glad to say that the net-utility is positive.
And the fact that Rust is being used quadruples my interest in contributing.
Therefore, are there any trivial fixes or new trivial features that I can contribute to?

**Comment by PaddiM8** [comment]
That's great the hear, thank you! I updated the kanban (the "In Progress" column is the one with tasks that should be worked on next) with relevant new features/fixes that should be implemented. I'll try to think of some more trivial features/fixes.

 https://kolan.strct.net/Board/4RAdMjLDz
