### ISSUE TITLE
Use of decimal comma

### ISSUE THREAD

**Issue by mhaustein** [PaddiM8/kalker#54]
Is there a way to configure kalker to use a decimal comma instead of the decimal point, like defining a locale? (I can remap my numeric keypad, but that doesn't help with copy-pasting numbers from and to other applications.)

**Comment by PaddiM8** [comment]
Hmm, it is not currently possible, and I'm not sure it is worth implementing. Commas are already used for when you have multiple function arguments, so it would get a bit ambiguous. It's certainly doable, but I feel like it would add unnecessary complexity. I'll close the issue for now, but the situation may change...
