### ISSUE TITLE
Support hexadecimal numbers

### ISSUE THREAD

**Issue by not-matthias** [PaddiM8/kalker#77]
Hexadecimal numbers would make this really useful for programmers. This could also just be a function (`hex(0x123ABC)`).

**Comment by PaddiM8** [comment]
This is now supported either by doing eg. `0xff` or `ff_16`.

**Comment by PaddiM8** [comment]
More extensive functionality is tracked at #80

**Comment by not-matthias** [comment]
Awesome, thank you!
