### ISSUE TITLE
Trigonometric functions with degrees not convenient

### ISSUE THREAD

**Issue by chemPolonium** [PaddiM8/kalker#96]
When I want to calculate sin(90deg) without brackets this is what I got:
```
>> sin 90deg
0.0156031853 rad
```
which is actually:
```
>> (sin 90)deg
0.0156031853 rad
```
Maybe the "deg" can have a higher order in calculation?

By the way, If the function is provided with "degrees"
```
>> sin (90deg)
1 rad
```
the "rad" after "sin" "cos" "tan" still exists. But these functions should "eat" the "rad".

**Comment by PaddiM8** [comment]
This should now be fixed on master. This was due to an issue with precedence for parenthesis-less calls in general. `sin90deg` now returns just `1`! Thanks for letting me know about this.
